# Generated by Django 4.0.4 on 2022-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_groupchatroom_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatroom',
            name='joined_users_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
