# Generated by Django 4.0.4 on 2022-05-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_groupchat_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatmessageseen',
            old_name='receiver',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='groupchatmessageseen',
            name='sender',
        ),
    ]
